apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-leader
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: test-leader
  template:
    metadata:
      labels:
        app.kubernetes.io/name: test-leader
    spec:
      serviceAccountName: test-leader
      containers:
        - name: leader
          image: go.seankhliao.com/test-leaderelection/cmd/leader
          imagePullPolicy: IfNotPresent
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
